## Redirects to new website
[[redirects]]
  from = "/"
  to = "https://orientation-website.vercel.app/"
  status = 301
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
